urls.py
from django.conf.urls import url
from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'pluton'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^home/$',views.home,name='home'),
    url(r'^culturals/$',views.culturals,name='culturals'),
    url(r'^scitech/$',views.scitech,name='scitech'),
    url(r'^sports/$',views.sports,name='sports'),
    url(r'^artlit/$',views.artlit,name='artlit'),
    url(r'^streetplay/$',views.streetplay,name='streetplay'),
    url(r'^westernband/$',views.westernband,name='westernband'),
    url(r'^photography/$',views.photography,name='photography'),
    url(r'^hackathon/$',views.hackathon,name='hackathon'),
    url(r'^sciencequiz/$',views.sciencequiz,name='sciencequiz'),
    url(r'^ctf/$',views.ctf,name='ctf'),
    url(r'^about/$',views.about,name='about'),
    url(r'^chess/$',views.chess,name='chess'),
    url(r'^chatbot/$',views.chatbot,name='chatbot'),
    url(r'^basketball/$',views.basketball,name='basketball'),
    url(r'^themepaint/$',views.themepaint,name='themepaint'),
    url(r'^creativewriting/$',views.creativewriting,name='creativewriting'),

    url(r'^registerevent1/$',views.registerevent1,name='registerevent1'),
    url(r'^payment/$', views.payment, name='payment'),
   
    url(r'^succ/$',views.succ,name='succ'),
    url(r'^logout/$', views.user_logout, name='logout'),
    #path('subscribe/', views.subscribe, name = 'subscribe'),
]

templates/pluton/base.html
<!DOCTYPE html>
<html>
  {% load static %}
<link rel='stylesheet' href="{% static 'pluton/style.css' %}">

  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <style>
      ul {
      
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
      }
      .button {
	background-color:yellow;
	border: none;
	color:white;
	padding: 15px 32px;
	text-align: center;
	text-decoration: none;
	display: inline-block;
	font-size: 16px;
	margin: 4px 2px;
	cursor: pointer;
  }


.button2 {background-color: #008CBA;} /* Blue */
.button3 {background-color: #f44336;} /* Red */ 
.button4 {background-color: #e7e7e7; color: black;} /* Gray */ 
.button5 {background-color: yellow;}
      li {
        float: left;
      }
      
      li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }
      
      li a:hover {
        background-color: #111;
      }


body {
  font-family: Arial, Helvetica, sans-serif;
}
.myBox {
border: none;
padding: 5px;
font: 24px/36px sans-serif;
width: 1500px;
height: 680px;
background-color: white;
}

.flip-card {
  background-color: transparent;
  width: 300px;
  height: 300px;
  perspective: 1000px;
}

.flex-container {
  display: flex;
  padding-top:50px;
  padding-left: 200px ;
  z-index: -1;
  background-color:white;
  clear :right;
}
.flex-container1 {
  display: flex;
  padding-left: 200px ;
  z-index: -1;
  background-color: white;
  clear :right;
}

.flex-container > div {
  background-color:white ;
  margin: 10px;
  padding: 10px;
  font-size: 30px;
}
.flex-container1 > div {
  background-color:white ;
  margin: 10px;
  padding: 10px;
  font-size: 30px;
}
#head{
  color: black;
  font-family: 'Karma';
  font-size: 50px;
  text-align: center;
}

#heading{
font-size:70px;
text-align: center;
}

.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.6s;
  transform-style: preserve-3d;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}

.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
}

.flip-card-front {
  background-color: #bbb;
  color:#333;
}

.flip-card-back {
  background-color:white;
  color: black;
  transform: rotateY(180deg);
}
#head{
  color: black;
  font-family: 'Karma';
  font-size: 50px;
  text-align: center;
}
</style>
</head>
  <body>    

     <img src="{% static "pluton/title.png" %}"  style="width:500px;height:100px;">
      <div class="container">
        <ul>
{# Django Home Link / Admin Link / Register Link#}


            <li><a class="navbar-brand" href="{% url 'pluton:index' %}">DJANGO</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="#chatbot" href="{% url 'pluton:chatbot' %}">FAQbot</a></li>
            <li><a class="navbar-link" href="{% url 'pluton:register' %}">Register</a></li>     
            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}
              <li><a href="{% url 'pluton:logout' %}">Logout</a></li>
            {% else %}
              <li><a class="navbar-link" href="{% url 'pluton:user_login' %}">Login</a></li>
            {% endif %}








</ul>

</br>
</br>


  

    <div class="container">
    {% block body_block %}
    {% endblock %}


  </br>
</br>
</br>
  </br>    </br>

</br>
</br>
</br>
</br>


  
  <footer class="footer-distributed">

    <div class="footer-left">
 
    <h3>PLUTON FIESTA</h3>
 
    <p class="footer-links">
 
   ·
    <a href="{% url 'pluton:about' %}">AboutUs</a>
  ·
    


  ·
    </p>
 
    <p class="footer-company-name">PlutonFiesta &copy; 2020</p>
    </div>
 
    <div class="footer-center">
 
    <div>
    <i class="fa fa-map-marker"></i>
    <p><span>PES University,B-block,G09 </span> Banglore, India</p>
    </div>
 
    <div>
    <i class="fa fa-phone"></i>
    <p>+91 9490956789</p>
    </div>
 
    <div>
    <i class="fa fa-envelope"></i>
    <p><a href="#">contact@plutonfiesta2020.com</a></p>
    </div>
 
    </div>
 
    <div class="footer-right">
 
    <p class="footer-company-about">
    <span>About the company</span>
  Pluton Fiesta is a website for fests .
    </p>
 
 
    </div>
 
    </div>
 
    </footer>
  
  </body>
</html>

templates/pluton/base1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'pluton:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'pluton:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'pluton:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'pluton:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/pluton/basketball.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

    <div class="myBox">
      <div class="flex-container" >

       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/bas.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
    
    <h2>BASKETBALL</h2>
    <p>
      Date : June 3 2020 </br> Time : 10:30pm
    </p>
    <button class="button" style="align-content: left;" > <a href="{% url 'pluton:registerevent1' %}" style="text-decoration:none" >REGISTER</a></button> 
          
       </div>
      </div>
     </div>
     <div style="width:750px;height:750px;border:5px solid #000;">
      <pre><h6>
        <u>RULES AND REGULATIONS</u>
        • Each game round will be 25 minutes with an
           immediate turnaround after each event.
        • Sound signals will indicate the start
           and the finish of each game.
        • Teams must register a minimum of 3 players 
           and a maximum of 5 players.
        • No players may be added to, or changes made to
           a team registration form after Round 1.
        • All teams must wear similar uniforms, and 
           the shirts must be clearly numbered.                        
        • Decision of Judges will be final and binding on all teams<b>
        • Registration fee: Rs 150 per team</b>
        • Winner: Rs 3000 
        • Runner: Rs 1500
              </h6>
    </div>

    

     </div>
     </div>
    <br>

    </div>
  </div>
</br>
</br>
</br>


{% endblock %}

templates/pluton/ctf.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

    <div class="myBox">
      <div class="flex-container" >

       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/ctf.png" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
    
    <h2>CTF</h2>
    <h6>
      Date : June 3 2020 </br> Time : 12:30pm
    </h6>
    <button class="button" style="align-content: left;" > <a href="{% url 'pluton:registerevent1' %}" style="text-decoration:none" >REGISTER</a></button> 
          
       </div>
      </div>
     </div>
     <div style="width:750px;height:750px;border:5px solid #000;">
      <pre><h6>
        <u>RULES AND REGULATIONS</u>
        * Only team entries are eligible, and team 
          shall consist of three persons 
        * The decision of the quiz-master will be final
          and will not be subjected to any change. 
        * The participants shall not be allowed to
          use mobile or other electronic devices.
        * The questions shall be in the form of
          multiple choice, True / False statement, etc. 
        * Audience/Supporters shall not give any 
          hints or clues to the competitors. 
        * Replacement of any participant of a
          team is not allowed after registration        
        * Decision of Judges will be final and 
          binding on all teams<b>
        *	Registration fee:<u>Rs 300 per team</u>
        *	Winner: Rs 3000 
        *	Runner: Rs 1500
        *	Any queries? contact: XYZ – 9876543219
      </h6>
    </div>

    

     </div>
     </div>
    <br>

    </div>
  </div>
</br>
</br>
</br>


{% endblock %}

templates/pluton/culturals.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

<div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}




    
    <div class="myBox" style="padding-left: 300px;">
      <p style="font-size: 50px; padding-left: 150px;" >CULTURAL EVENTS</p>
      <div class="flex-container" >
       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/st.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
      </br>
    </br>
          <button class="button button5" > <a href="{% url 'pluton:streetplay' %}" style="text-decoration:none" >STREETPLAY</a></button>
          
       </div>
      </div>
     </div>
     <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{% static "pluton/wb.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        </div>
        <div class="flip-card-back">
       </br>
     </br>
   </br>
         <button class="button button5" > <a href="{% url 'pluton:westernband' %}" style="text-decoration:none" >WESTERN BAND</a></button>
    
        </div>
      </div>
      </div>

      </div>


    {% else %}
    <h2>Register or Login </h2>
{% endif %}

{% endblock %}

templates/pluton/hackathon.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

    <div class="myBox">
      <div class="flex-container" >

       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/hac.png" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
    
    <h2>HACKATHON</h2>
    <h6>
      Date : June 3 2020 </br> Time : 8:30am
    </h6>
    <button class="button" style="align-content: left;" > <a href="{% url 'pluton:registerevent1' %}" style="text-decoration:none" >REGISTER</a></button> 
          
       </div>
      </div>
     </div>
     <div style="width:750px;height:750px;border:5px solid #000;">
      <pre><h6>
        <u>RULES AND REGULATIONS</u>
        • All design elements, code, hardware builds, etc. 
         for your project must be created during the event.
        • Third party tools and frameworks are allowed
          as well as your normal tooling 
        • Teams must be comprised of 1-4 people.
        • Only ten of the competing teams will present their projects 
          in the final round of judging at the end of the event. 
        • The presenting teams will be determined by an initial 
          round of judging that will take place during the final 
             1.5 hours of the event. 
        • Teams that make it to the final round will be given up to 
          three minutes to present their finished project
            to a panel of judges.        
        • Decision of Judges will be final and binding on all teams<b>
        • Registration fee: Rs 300 per team</b>
        • Winner: Rs 3000 
        • Runner: Rs 1500
    </h6>
  </div>

  

   </div>
   </div>
  <br>

  </div>
</div>
</br>
</br>
</br>


{% endblock %}

templates/pluton/home.html
{% extends 'pluton/base.html' %}
{% block body_block %}

{% load static %}
<div class="container">
  <div class="jumbotron">

    {% if user.is_authenticated %}


    <div class="myBox">
      <p id ="head" >DOMAINS</p>
      <div class="flex-container" >
       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/cul.png" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
      </br>
    </br>
          <button class="button button5" > <a href="{% url 'pluton:culturals' %}" style="text-decoration:none" >Culturals</a></button>
          
       </div>
      </div>
     </div>
     <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{% static "pluton/sat.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        </div>
        <div class="flip-card-back">
       </br>
     </br>
   </br>
         <button class="button button5" > <a href="{% url 'pluton:scitech' %}" style="text-decoration:none" >Science and Technology</a></button>
    
        </div>
      </div>
      </div>

      </div>

    

    <div class="myBox" style="padding-left: 300px;">
      <div class="flex-container" >
       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/art.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
      </br>
    </br>
          <button class="button button5" > <a href="{% url 'pluton:artlit' %}" style="text-decoration:none" >Art and Literature</a></button>
          
       </div>
      </div>
     </div>
     <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{% static "pluton/spo.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        </div>
        <div class="flip-card-back">
       </br>
     </br>
   </br>
         <button class="button button5" > <a href="{% url 'pluton:sports' %}" style="text-decoration:none" >Sports</a></button>
    
        </div>
      </div>
      </div>

      </div>


<!--







       <div class="flex-container" style="padding-left: 300px;" >
        <div class="flip-card">
          <div class="flip-card-inner">
            <div class="flip-card-front">
              <img src="{% static "pluton/spo.jpg" %}"alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip-card-back">
            </br>
           </br>
         </br>
             <button  class="button button5" > <a href="{% url 'pluton:sports' %}" style="text-decoration:none" >Sports</a></button>
               
            </div>
          </div>
          </div>
          </div>
          <div class="flip-card">
            <div class="flip-card-inner">
              <div class="flip-card-front">
                <img src="{% static "pluton/sat.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
              </div>
              <div class="flip-card-back">
             </br>
           </br>
         </br>
               <button class="button button5" > <a href="{% url 'pluton:scitech' %}" style="text-decoration:none" >Science and Technology</a></button>
          
              </div>
            </div>
            </div>
      

     </div>
     </div>
    <br>
    -->
    
  </div>
</div>
{% else %}
<h2>Register or Login </h2>
{% endif %}
{% endblock %}

templates/pluton/index.html
{% extends 'pluton/base.html' %}
{% block body_block %}

{% load static %}
<div class="container">
  <div class="jumbotron">

    {% if user.is_authenticated %}


    <div class="myBox">
      <p id ="head" >DOMAINS</p>
      <div class="flex-container" >
       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/cul.png" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
      </br>
    </br>
          <button class="button button5" > <a href="{% url 'pluton:culturals' %}" style="text-decoration:none" >Culturals</a></button>
          
       </div>
      </div>
     </div>
     <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{% static "pluton/sat.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        </div>
        <div class="flip-card-back">
       </br>
     </br>
   </br>
         <button class="button button5" > <a href="{% url 'pluton:scitech' %}" style="text-decoration:none" >Science and Technology</a></button>
    
        </div>
      </div>
      </div>

      </div>

     





      

    <div class="myBox" style="padding-left: 300px;">
      <div class="flex-container" >
       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/art.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
      </br>
    </br>
          <button class="button button5" > <a href="{% url 'pluton:artlit' %}" style="text-decoration:none" >Art and Literature</a></button>
          
       </div>
      </div>
     </div>
     <div class="flip-card">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{% static "pluton/spo.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        </div>
        <div class="flip-card-back">
       </br>
     </br>
   </br>
         <button class="button button5" > <a href="{% url 'pluton:sports' %}" style="text-decoration:none" >Sports</a></button>
    
        </div>
      </div>
      </div>

      </div>

    {% else %}
        <h2 style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; padding-left: 200px;"> REGISTER OR LOGIN TO LOOK INTO THE EVENTS! </h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/pluton/payment.html
{% extends "pluton/base.html" %}
{% load static %}
{% block body_block %}
<h1>PAYMENT</h1>
  <div class="container">
    <div class="jumbotron">
      {% if paid %}
        <h1>Thank you for registering to the event!</h1>
      {% else %}
        <h1>Pay Here</h1>
        <h3>Just fill the details to complete payment.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ payment_form.as_p }}
          <h3>Total Amount </h3>
          <input type="submit" name="" value="Payment">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/pluton/photography.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

    <div class="myBox">
      <div class="flex-container" >

       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/pic.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
    
    <h3>PHOTOGRAPHY</h3>
    <h6>
      Date : June 3 2020 </br> Time : 3:30pm
    </h6>
    <button class="button" style="align-content: left;" > <a href="{% url 'pluton:registerevent1' %}" style="text-decoration:none" >REGISTER</a></button> 
          
       </div>
      </div>
     </div>
     <div style="width:750px;height:750px;border:5px solid #000;">
      <pre><h6>
        <u>RULES AND REGULATIONS</u>
        • The photo must be in its original
         state and cannot be altered in any way
        • Violators will be removed from the contest, 
          stripped of any prize(s).
        • Submissions will not be accepted
          once the deadline lapses.
        • No Cameras or any material will be
          provided by the host college.        
        • Decision of Judges will be final and 
          binding on all teams<b>
        • Registration fee: Rs 200</b>
        • Winner: Rs 3000 
        • Runner: Rs 1500


    </h6>
  </div>

  

   </div>
   </div>
  <br>

  </div>
</div>
</br>
</br>
</br>


{% endblock %}

templates/pluton/registerevent1.html
{% extends "pluton/base.html" %}
{% load static %}
{% block body_block %}
<h1> EVENT REGISTERATION </h1>
  <div class="container">
    <div class="jumbotron">
      {% if registeredevent %}
        <h1>Proceed to payment to finish registeration</h1>
      {% else %}
        <h1>Event Registeration</h1>
        <h3>Just fill the details to register for event.</h3>
       <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{regevent_form.as_p }}
          <input type="submit" name="" value="Proceed to Pay">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/pluton/registration.html
{% extends "pluton/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register" style="background-color: yellow;"/>
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/pluton/sciencequiz.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

    <div class="myBox">
      <div class="flex-container" >

       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/qu.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
    
    <h2>SCIENCE QUIZ</h2>
    <h6>
      Date : June 3 2020 </br> Time : 10:00am
    </h6>
    <button class="button" style="align-content: left;" > <a href="{% url 'pluton:registerevent1' %}" style="text-decoration:none" >REGISTER</a></button> 
          
       </div>
      </div>
     </div>
     <div style="width:750px;height:750px;border:5px solid #000;">
      <pre><h6>
        <u>RULES AND REGULATIONS</u>
        • Only team entries are eligible, and team 
         shall consist of three persons 
        • The decision of the quiz-master will be 
          final and will not be subjected to any change. 
        • The participants shall not be allowed to 
        use mobile or other electronic devices.
        • The questions shall be in the form of multiple
         choice, True / False statement, etc. 
        • Audience/Supporters shall not give any hints 
        or clues to the competitors. 
        • Replacement of any participant of a team 
        is not allowed after registration        
        • Decision of Judges will be final and 
        binding on all teams<b>
        • Registration fee: Rs 300 per team</b>
        • Winner: Rs 3000 
        • Runner: Rs 1500

      </h6>
    </div>

    

     </div>
     </div>
    <br>

    </div>
  </div>
</br>
</br>
</br>


{% endblock %}

templates/pluton/streetplay.html
{% extends 'pluton/base.html' %}
{% block body_block %}
{% load static %}

    <div class="myBox">
      <div class="flex-container" >

       <div class="flip-card">
        <div class="flip-card-inner">
         <div class="flip-card-front">
           <img src="{% static "pluton/st.jpg" %}" style="width:300px;height:300px;">
         </div>
        <div class="flip-card-back">
        </br>
    
    <h2>STREET PLAY</h2>
    <h6>
      Date : June 3 2020 </br> Time : 10:30pm
    </h6>
    <button class="button" style="align-content: left;" > <a href="{% url 'pluton:registerevent1' %}" style="text-decoration:none" >REGISTER</a></button> 
          
       </div>
      </div>
     </div>
     <div style="width:750px;height:750px;border:5px solid #000;">
      <pre><h6>
        <u>RULES AND REGULATIONS</u>
        • The Competition will be conducted in a “Street” 
        • No microphones, Speakers, Music systems 
          will be allowed or available. 
        • No Props or costume or any material will 
         be provided by the host college.
        • Decision of Judges will be final
           and binding on all teams.<b>
        • Registration fee: Rs 200</b>
        • Winner: Rs 3000 
        • Runner: Rs 1500
        •	Any queries? contact : XYZ – 9876543219

      </h6>
    </div>

    

     </div>
     </div>
    <br>

    </div>
  </div>
</br>
</br>
</br>


{% endblock %}